import 'package:procurement_scanner/models/item.dart';
import 'package:procurement_scanner/models/location.dart';
import 'package:procurement_scanner/models/transaction.dart';

/// Generate mock locations
/// Based on Materials in Warehouse structure
List<Location> generateMockLocations() {
  return [
    const Location(
      id: 'loc-1',
      name: 'Main Warehouse',
      description: 'Primary storage facility',
      address: '123 Industrial Blvd, City, State 12345',
      isWarehouse: true,
      warehouseCode: 'WH-001',
    ),
    const Location(
      id: 'loc-2',
      name: 'Distribution Center',
      description: 'Secondary distribution hub',
      address: '456 Commerce St, City, State 12345',
      isWarehouse: true,
      warehouseCode: 'WH-002',
    ),
    const Location(
      id: 'loc-3',
      name: 'Office Storage',
      description: 'On-site office storage',
      address: '789 Business Park, City, State 12345',
      isWarehouse: false,
    ),
    const Location(
      id: 'loc-4',
      name: 'Remote Warehouse A',
      description: 'Remote warehouse location A',
      isWarehouse: true,
      warehouseCode: 'WH-003',
    ),
    const Location(
      id: 'loc-5',
      name: 'Office Stock Room',
      description: 'Office stock room',
      isWarehouse: false,
    ),
  ];
}

/// Generate mock items
/// Based on MATERIAL DATA SHEET structure
List<Item> generateMockItems() {
  final now = DateTime.now();
  return [
    Item(
      id: 'item-1',
      materialCode: 'MAT-001',
      name: 'Laptop Computer',
      description: 'Dell Latitude 7420 Laptop',
      specification: 'Intel Core i7, 16GB RAM, 512GB SSD',
      unitOfMeasure: 'pcs',
      barcode: '1234567890123',
      nfcId: 'nfc-001',
      currentLocation: 'loc-1',
      quantity: 15,
      category: 'Electronics',
      supplier: 'TechCorp Inc.',
      notes: 'Dell Latitude series',
      isOfficeStock: false,
      createdAt: now.subtract(const Duration(days: 30)),
      updatedAt: now.subtract(const Duration(days: 2)),
    ),
    Item(
      id: 'item-2',
      materialCode: 'MAT-002',
      name: 'Office Chair',
      description: 'Ergonomic Office Chair',
      specification: 'Adjustable height, lumbar support',
      unitOfMeasure: 'pcs',
      barcode: '2345678901234',
      currentLocation: 'loc-3',
      quantity: 8,
      category: 'Furniture',
      supplier: 'Furniture Plus',
      notes: 'Ergonomic design',
      isOfficeStock: true,
      createdAt: now.subtract(const Duration(days: 25)),
      updatedAt: now.subtract(const Duration(days: 5)),
    ),
    Item(
      id: 'item-3',
      materialCode: 'MAT-003',
      name: 'Printer Paper',
      description: 'A4 Printer Paper',
      specification: 'A4 size, 80gsm, white',
      unitOfMeasure: 'ream',
      barcode: '3456789012345',
      currentLocation: 'loc-2',
      quantity: 120,
      category: 'Office Supplies',
      supplier: 'Supply Co.',
      notes: 'A4 size, 80gsm',
      isOfficeStock: false,
      createdAt: now.subtract(const Duration(days: 20)),
      updatedAt: now.subtract(const Duration(days: 1)),
    ),
    Item(
      id: 'item-4',
      materialCode: 'MAT-004',
      name: 'Projector',
      description: 'HD Projector',
      specification: 'HD 1080p, 3500 lumens',
      unitOfMeasure: 'pcs',
      barcode: '4567890123456',
      nfcId: 'nfc-002',
      currentLocation: 'loc-1',
      quantity: 3,
      category: 'Electronics',
      supplier: 'TechCorp Inc.',
      notes: 'HD 1080p',
      isOfficeStock: false,
      createdAt: now.subtract(const Duration(days: 15)),
      updatedAt: now.subtract(const Duration(days: 3)),
    ),
    Item(
      id: 'item-5',
      materialCode: 'MAT-005',
      name: 'Desk Lamp',
      description: 'LED Desk Lamp',
      specification: 'LED, adjustable brightness',
      unitOfMeasure: 'pcs',
      barcode: '5678901234567',
      currentLocation: 'loc-3',
      quantity: 25,
      category: 'Furniture',
      supplier: 'Furniture Plus',
      isOfficeStock: true,
      createdAt: now.subtract(const Duration(days: 10)),
      updatedAt: now.subtract(const Duration(days: 7)),
    ),
    Item(
      id: 'item-6',
      materialCode: 'MAT-006',
      name: 'Network Switch',
      description: 'Managed Network Switch',
      specification: '24-port, Gigabit, managed',
      unitOfMeasure: 'pcs',
      barcode: '6789012345678',
      nfcId: 'nfc-003',
      currentLocation: 'loc-2',
      quantity: 5,
      category: 'Electronics',
      supplier: 'Networking Solutions',
      notes: '24-port managed switch',
      isOfficeStock: false,
      createdAt: now.subtract(const Duration(days: 8)),
      updatedAt: now.subtract(const Duration(hours: 12)),
    ),
    Item(
      id: 'item-7',
      materialCode: 'MAT-007',
      name: 'Storage Boxes',
      description: 'Cardboard Storage Boxes',
      specification: 'Medium size, cardboard',
      unitOfMeasure: 'pcs',
      barcode: '7890123456789',
      currentLocation: 'loc-4',
      quantity: 50,
      category: 'Storage',
      supplier: 'Supply Co.',
      notes: 'Cardboard, medium size',
      isOfficeStock: false,
      createdAt: now.subtract(const Duration(days: 5)),
      updatedAt: now.subtract(const Duration(days: 1)),
    ),
    Item(
      id: 'item-8',
      materialCode: 'MAT-008',
      name: 'Monitor Stand',
      description: 'Adjustable Monitor Stand',
      specification: 'Adjustable height, fits 13-27 inch monitors',
      unitOfMeasure: 'pcs',
      barcode: '8901234567890',
      currentLocation: 'loc-1',
      quantity: 12,
      category: 'Furniture',
      supplier: 'Furniture Plus',
      isOfficeStock: false,
      createdAt: now.subtract(const Duration(days: 3)),
      updatedAt: now.subtract(const Duration(hours: 6)),
    ),
  ];
}

/// Generate mock transactions
/// Based on Office Stock Register structure
List<Transaction> generateMockTransactions() {
  final now = DateTime.now();
  return [
    Transaction(
      id: 'txn-1',
      itemId: 'item-1',
      materialCode: 'MAT-001',
      type: TransactionType.transfer,
      fromLocation: 'loc-1',
      toLocation: 'loc-2',
      quantity: 5,
      unitOfMeasure: 'pcs',
      timestamp: now.subtract(const Duration(hours: 2)),
      userId: 'user-1',
      remarks: 'Transfer to distribution center',
    ),
    Transaction(
      id: 'txn-2',
      itemId: 'item-3',
      materialCode: 'MAT-003',
      type: TransactionType.scanIn,
      toLocation: 'loc-2',
      quantity: 50,
      unitOfMeasure: 'ream',
      timestamp: now.subtract(const Duration(hours: 5)),
      userId: 'user-1',
      remarks: 'New stock received',
    ),
    Transaction(
      id: 'txn-3',
      itemId: 'item-6',
      materialCode: 'MAT-006',
      type: TransactionType.scanOut,
      fromLocation: 'loc-2',
      quantity: 2,
      unitOfMeasure: 'pcs',
      timestamp: now.subtract(const Duration(hours: 8)),
      userId: 'user-2',
      remarks: 'Issued for installation',
    ),
    Transaction(
      id: 'txn-4',
      itemId: 'item-4',
      materialCode: 'MAT-004',
      type: TransactionType.transfer,
      fromLocation: 'loc-1',
      toLocation: 'loc-3',
      quantity: 1,
      unitOfMeasure: 'pcs',
      timestamp: now.subtract(const Duration(days: 1)),
      userId: 'user-1',
      remarks: 'Transfer to office',
    ),
    Transaction(
      id: 'txn-5',
      itemId: 'item-2',
      materialCode: 'MAT-002',
      type: TransactionType.scanIn,
      toLocation: 'loc-3',
      quantity: 3,
      unitOfMeasure: 'pcs',
      timestamp: now.subtract(const Duration(days: 2)),
      userId: 'user-2',
      remarks: 'Office stock addition',
    ),
    Transaction(
      id: 'txn-6',
      itemId: 'item-7',
      materialCode: 'MAT-007',
      type: TransactionType.transfer,
      fromLocation: 'loc-2',
      toLocation: 'loc-4',
      quantity: 20,
      unitOfMeasure: 'pcs',
      timestamp: now.subtract(const Duration(days: 3)),
      userId: 'user-1',
      remarks: 'Transfer to remote warehouse',
    ),
    Transaction(
      id: 'txn-7',
      itemId: 'item-5',
      materialCode: 'MAT-005',
      type: TransactionType.scanOut,
      fromLocation: 'loc-3',
      quantity: 5,
      unitOfMeasure: 'pcs',
      timestamp: now.subtract(const Duration(days: 4)),
      userId: 'user-2',
      remarks: 'Office stock issued',
    ),
    Transaction(
      id: 'txn-8',
      itemId: 'item-8',
      materialCode: 'MAT-008',
      type: TransactionType.scanIn,
      toLocation: 'loc-1',
      quantity: 12,
      unitOfMeasure: 'pcs',
      timestamp: now.subtract(const Duration(days: 5)),
      userId: 'user-1',
      remarks: 'New stock received',
    ),
  ];
}

